name: CI

on:
  push:
    branches:
      - $defualt-branch
  pull_request:
    branches:
      - $default-branch 
  workflow_dispatch:

jobs:
  ci:
    uses: ausseabed/.github/.github/workflows/ci.yaml@main
    secrets:
        prefix_api_token: ${{ secrets.PREFIX_API_KEY }}